from exercises import variant_1
from exercises import variant_2
from exercises import variant_3
from exercises import variant_4
from exercises import variant_5
from exercises import variant_6
from exercises import variant_7
from exercises import variant_8
from exercises import variant_9
from exercises import variant_10
from exercises import variant_11
from exercises import variant_12
from exercises import variant_13
from exercises import variant_14
from exercises import variant_15
from exercises import variant_16
from exercises import variant_17
from exercises import variant_18
from exercises import variant_19
from exercises import variant_20
from exercises import variant_21
from exercises import variant_22
from exercises import variant_23
from exercises import variant_24
from exercises import variant_25
from exercises import variant_26
from exercises import variant_27
from exercises import variant_28
from exercises import variant_29
from exercises import variant_30
from exercises import variant_31
from exercises import variant_32
from exercises import variant_33
from exercises import variant_34
from exercises import variant_35